language: python

python:
  - 2.7
  - 3.2
  - 3.3
  - 3.4
  - 3.5

before_install:
  - pip install coveralls

install:
  - pip install -e .
  - pip install -r requirements_dev.txt
  - pip install Django==${DJANGO}

script: coverage run --source pong runtests.py tests

env:
  - DJANGO=1.8.11
  - DJANGO=1.9.4

matrix:
  exclude:
    - python: 3.2
      env: DJANGO=1.9.4
    - python: 3.3
      env: DJANGO=1.9.4

after_success:
  - coveralls
